######################################################################
# Automatically generated by qmake (3.0) ma maj 25 20:25:52 2015
######################################################################

TEMPLATE = app
TARGET = miditest
LIBS += -lrtmidi
QT += gui widgets
QMAKE_CXXFLAGS += -std=c++14

# Input
#HEADERS += 
SOURCES += src/main.cpp
