######################################################################
# Automatically generated by qmake (3.0) ma maj 25 20:25:52 2015
######################################################################

TEMPLATE = app
TARGET = miditest
#LIBS += -lrtmidi
INCLUDEPATH += deps/include /usr/include/guido
QT += gui widgets printsupport
QMAKE_CXXFLAGS += -std=c++14

# Input
#HEADERS += 
SOURCES += src/main.cpp

LIBS += -Ldeps/libs -lGuidoQt
LIBS += -lGUIDOEngine
